repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.0  # pin a version
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs
          - types-requests
        args:
          - --config-file=mypy.ini
